/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import static Vista.AsignarMedico.arbolito;
import static Vista.Interfaz.MostrarListaEspera;
import static Vista.Interfaz.MostrarListaPacientes;
import static Vista.NuevoPaciente.colaMascotas;

/**
 *
 * @author Kryssia Pizarro
 */
public class MostrarInfoHospital extends javax.swing.JFrame {

    /**
     * Creates new form MostrarInformacionHospital
     */
    public MostrarInfoHospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textAreaInformación = new java.awt.TextArea();
        BTNAcepta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Información Diagnósticos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 320, -1));

        textAreaInformación.setEditable(false);
        textAreaInformación.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(textAreaInformación, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 250, 260));

        BTNAcepta.setBackground(new java.awt.Color(0, 204, 102));
        BTNAcepta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNAcepta.setForeground(new java.awt.Color(255, 255, 255));
        BTNAcepta.setText("ACEPTAR");
        BTNAcepta.setBorderPainted(false);
        BTNAcepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAceptaActionPerformed(evt);
            }
        });
        jPanel1.add(BTNAcepta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNAceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAceptaActionPerformed
        this.dispose();
	new Interfaz().setVisible(true);
        MostrarListaPacientes.setText(colaMascotas.imprimir());
        MostrarListaEspera.setText(arbolito.toString());
    }//GEN-LAST:event_BTNAceptaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarInfoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarInfoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarInfoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarInfoHospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarInfoHospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAcepta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static java.awt.TextArea textAreaInformación;
    // End of variables declaration//GEN-END:variables
}
